apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform
resources:
  - authelia.yaml
  - grafana-oauth.yaml
  - postgresql-backup-auth.yaml
  - grafana-admin.yaml
  - registry-auth.yaml
  - s3-backup.yaml
