apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiny-screen-api
  namespace: applications
  labels:
    app.kubernetes.io/name: tiny-screen-api
    app.kubernetes.io/instance: tiny-screen-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tiny-screen-api
      app.kubernetes.io/instance: tiny-screen-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tiny-screen-api
        app.kubernetes.io/instance: tiny-screen-api
    spec:
      containers:
      - name: tiny-screen-api
        image: registry.lvs.me.uk/tiny-screen-api:1.0.47 # {"$imagepolicy": "flux-system:tiny-screen-api"}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 4567
          protocol: TCP
        resources:
          requests:
            cpu: "10m"
            memory: "10Mi"
          limits:
            cpu: "50m"
            memory: "100Mi"
        env:
          - name: APP_VERSION
            value: "1.0.47"
          - name: RACK_ENV
            value: production
