apiVersion: v1
kind: Service
metadata:
  name: tiny-screen-api
  namespace: applications
  labels:
    app.kubernetes.io/name: tiny-screen-api
    app.kubernetes.io/instance: tiny-screen-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: tiny-screen-api
    app.kubernetes.io/instance: tiny-screen-api
