apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-prometheus-stack.yaml
  - pushgateway.yaml
  - loki.yaml
  - promtail.yaml
  - alert-rules.yaml
  - alertmanager-config.yaml
  - s3-metrics-collector.yaml
patchesStrategicMerge:
  - grafana-pvc-backup.yaml
