apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - platform-namespace.yaml
  - applications-namespace.yaml
  - longhorn.yaml
  - jetstack.yaml
  - bitnami.yaml
  - grafana.yaml
  - prometheus-community.yaml
  - authelia.yaml
