apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - longhorn.yaml
  - jetstack.yaml
  - bitnami.yaml
  - grafana.yaml
  - prometheus-community.yaml
  - authelia.yaml
