apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vsmp-royalties
  namespace: applications
  labels:
    app.kubernetes.io/name: vsmp-royalties
    app.kubernetes.io/instance: vsmp-royalties
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: applications-authelia-forwardauth@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - royalties.lvs.me.uk
      secretName: vsmp-royalties-tls
  rules:
    - host: royalties.lvs.me.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vsmp-royalties
                port:
                  number: 80
