apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsmp-royalties-worker
  namespace: applications
  labels:
    app.kubernetes.io/name: vsmp-royalties
    app.kubernetes.io/instance: vsmp-royalties
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vsmp-royalties
      app.kubernetes.io/instance: vsmp-royalties
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vsmp-royalties
        app.kubernetes.io/instance: vsmp-royalties
        app.kubernetes.io/component: worker
    spec:
      containers:
      - name: vsmp-royalties-worker
        image: registry.lvs.me.uk/vsmp-royalties:1.0.52 # {"$imagepolicy": "flux-system:vsmp-royalties"}
        imagePullPolicy: Always
        command: ["bin/jobs"]
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        - name: APP_VERSION
          value: "1.0.48"
        - name: JOB_CONCURRENCY
          value: "1"
        - name: DB_HOST
          value: postgresql.platform.svc.cluster.local
        - name: DB_PORT
          value: "5432"
        - name: RAILS_ENV
          value: production
        - name: RAILS_LOG_TO_STDOUT
          value: "true"
        - name: RAILS_SERVE_STATIC_FILES
          value: "true"
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: vsmp-royalties-secrets
              key: master-key
      terminationGracePeriodSeconds: 60
