apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources.yaml
  - helmrepositories.yaml
  - storage-install.yaml
  - storage-config.yaml
  - cert-manager-install.yaml
  - cert-manager-config.yaml
  - registry.yaml
  - postgresql.yaml
  - monitoring.yaml
  - traefik-dashboard.yaml
  - image-automation.yaml
  - apps.yaml
