apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources.yaml
  - namespaces.yaml
  - platform-secrets.yaml
  - application-secrets.yaml
  - infrastructure-secrets.yaml
  - helmrepositories.yaml
  - storage-install.yaml
  - storage-config.yaml
  - cert-manager-install.yaml
  - cert-manager-config.yaml
  - registry.yaml
  - postgresql.yaml
  - redis.yaml
  - authelia.yaml
  - monitoring.yaml
  - traefik-dashboard.yaml
  - longhorn-dashboard.yaml
  - alertmanager.yaml
  - image-automation.yaml
  - ruby-demo-app.yaml
  - vsmp-royalties.yaml
