apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: applications
resources:
  - k8s/deployment.yaml
  - k8s/worker-deployment.yaml
  - k8s/service.yaml
  - k8s/ingress.yaml
commonLabels:
  app.kubernetes.io/name: vsmp-royalties
  app.kubernetes.io/instance: vsmp-royalties
