env:
  # Database connection
  - name: DB_HOST
    value: postgresql.platform.svc.cluster.local
  - name: DB_PORT
    value: "5432"

  # Rails
  - name: RAILS_ENV
    value: production
  - name: RAILS_LOG_TO_STDOUT
    value: "true"
  - name: RAILS_SERVE_STATIC_FILES
    value: "true"
  - name: RAILS_MASTER_KEY
    valueFrom:
      secretKeyRef:
        name: vsmp-royalties-secrets
        key: master-key
