---
# Traefik ForwardAuth middleware for Authelia SSO
# Copy of the authelia-forwardauth middleware for the monitoring namespace
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authelia-forwardauth
  namespace: monitoring
spec:
  forwardAuth:
    address: http://authelia.default.svc.cluster.local/api/authz/forward-auth
    trustForwardHeader: true
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
      - Remote-Email
      - Remote-Name
