apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepositories
  - storage-install
  - storage-config
  - cert-manager-install
  - cert-manager-config
  - postgresql-new
  - monitoring
  - traefik-dashboard
  - authelia
