{{- if .Values.worker.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vsmp-royalties.fullname" . }}-worker
  labels:
    {{- include "vsmp-royalties.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "vsmp-royalties.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "vsmp-royalties.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
      - name: {{ .Chart.Name }}-worker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["bin/jobs"]
        {{- with .Values.worker.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
          - name: APP_VERSION
            value: {{ .Values.image.tag | default .Chart.AppVersion | quote }}
          {{- with .Values.worker.env }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.env }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.envFrom }}
        envFrom:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      terminationGracePeriodSeconds: {{ .Values.worker.terminationGracePeriodSeconds }}
{{- end }}
