---
# Traefik ForwardAuth middleware for Authelia SSO
# Middleware for the applications namespace
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authelia-forwardauth
  namespace: applications
spec:
  forwardAuth:
    address: http://authelia.platform.svc.cluster.local/api/authz/forward-auth
    trustForwardHeader: true
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
      - Remote-Email
      - Remote-Name
