apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- secrets
- source-controller-storage.yaml
patches:
- patch: |
    - op: replace
      path: /spec/template/spec/volumes/0
      value:
        name: data
        persistentVolumeClaim:
          claimName: source-controller-data
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 512Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 128Mi
  target:
    kind: Deployment
    name: source-controller
