test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use bin/rails credentials:edit to set the Hetzner secrets (as aws:access_key_id|secret_access_key)
hetzner:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:hetnzer, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:hetzner, :secret_access_key) %>
  region: <%= Rails.application.credentials.dig(:hetzner, :region) %>
  bucket: <%= Rails.application.credentials.dig(:hetzner, :bucket) %>
  endpoint: <%= Rails.application.credentials.dig(:hetzner, :endpoint) %>
  force_path_style: true
